- hosts: all
  vars:
  - namenode_ip: "13.235.50.75"
  tasks:
  - name: "Copy JDK  in the  both Instances"
    copy:
      src: "/home/ec2-user/jdk-8u171-linux-x64.rpm"
      dest: "/root/"
  - name: "Copy hadoop  in the  both Instances"
    copy:
      src: "/home/ec2-user/hadoop-1.2.1-1.x86_64.rpm"
      dest: "/root/"
  - name: "Install JDk in both system"
    shell: "rpm -ivh /root/jdk-8u171-linux-x64.rpm"
    ignore_errors: yes
  - name: "Install Hadoop in both of the system"
    shell: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes

- hosts: namenode
  vars:
  - namenode_ip: "13.235.50.75"
  tasks:

  - name: "Configure hdfs-site.xml"
    template:
      dest: "/etc/hadoop/hdfs-site.xml"
      src: "/home/ec2-user/namenode/hdfs-site.xml"
  - name: "Configure core-site.xml"
    template:
      dest: "/etc/hadoop/core-site.xml"
      src: "/home/ec2-user/namenode/core-site.xml"
  - name: Creates directory
    file:
      path: /nn
      state: directory
  - name: "Format the namenode directory"
    shell: "echo Y | hadoop namenode -format"
  - name: "Start Namenode Service"
    shell: "hadoop-daemon.sh start namenode"

- hosts: datanode
  vars:
  - namenode_ip: "13.235.50.75"
    folder: /dn3
  tasks:

  - name: "Configure hdfs-site.xml"
    template:
      dest: "/etc/hadoop/hdfs-site.xml"
      src: "/home/ec2-user/datanode/hdfs-site.xml"
  - name: "Configure core-site.xml"
    template:
      dest: "/etc/hadoop/core-site.xml"
      src: "/home/ec2-user/datanode/core-site.xml"
  - name: "Creates directory"
    file:
      path: folder
      state: directory
  - name: "Start datanode Service"
    shell: "hadoop-daemon.sh start datanode"